spring:
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/jpa
    username: sa
    password: aaa
